# Generated by Django 4.2.16 on 2026-05-16 08:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('units', models.PositiveIntegerField()),
                ('year_level', models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5')])),
                ('semester', models.IntegerField(choices=[(1, '1st Semester'), (2, '2nd Semester'), (3, 'Summer')])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('max_students', models.PositiveIntegerField(default=40)),
                ('room', models.CharField(blank=True, max_length=50)),
                ('schedule', models.CharField(blank=True, max_length=100)),
                ('instructor', models.CharField(blank=True, max_length=100)),
                ('school_year', models.CharField(max_length=20)),
                ('semester', models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, 'Summer')])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='sections.subject')),
            ],
            options={
                'ordering': ['subject__code', 'name'],
                'unique_together': {('subject', 'name', 'school_year', 'semester')},
            },
        ),
    ]
